Enrollment No.:240840116005

Practical-2: Perform data inspection, cleaning, handling missing values, duplicate removal, and data transformation using Pandas.

Step 1:Import the Pandas Library

In [ ]:
import pandas as pd

Step 2:Create Sample Data

In [ ]:
# Create a dictionary containing sample student data

data={
    "ID": [101,102,103,104,104,105,106,107],
    "Name": ["Rahul","Karan","Riya",None,"Amit","Priya","Krisha","Harry"],
    "Age": [20,21,None,19,20,22,24,28],
    "City": ["Surat","Navsari","Valsad","Bharuch","Surat","Navsari","Valsad","Surat"],
    "Marks": [85,None,78,88,88,87,90,93]
}

Step 3:Create a DataFrame

In [ ]:
# Convert dictionary into a DataFrame

df = pd.DataFrame(data)

# Display the original dataset

df

    ID    Name   Age     City  Marks
0  101   Rahul  20.0    Surat   85.0
1  102   Karan  21.0  Navsari    NaN
2  103    Riya   NaN   Valsad   78.0
3  104    None  19.0  Bharuch   88.0
4  104    Amit  20.0    Surat   88.0
5  105   Priya  22.0  Navsari   87.0
6  106  Krisha  24.0   Valsad   90.0
7  107   Harry  28.0    Surat   93.0

Step 4: Data Inspection

Task 1: Display first 5 rows of dataset.

In [ ]:
# Display first 5 rows

df.head()

    ID   Name   Age     City  Marks
0  101  Rahul  20.0    Surat   85.0
1  102  Karan  21.0  Navsari    NaN
2  103   Riya   NaN   Valsad   78.0
3  104   None  19.0  Bharuch   88.0
4  104   Amit  20.0    Surat   88.0

Task 2: Display Last 5 rows of dataset.

In [ ]:
# Display last 5 rows

df.tail()

    ID    Name   Age     City  Marks
3  104    None  19.0  Bharuch   88.0
4  104    Amit  20.0    Surat   88.0
5  105   Priya  22.0  Navsari   87.0
6  106  Krisha  24.0   Valsad   90.0
7  107   Harry  28.0    Surat   93.0

Task 3: Display detailed information about the dataset.

In [ ]:
# Display complete information

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ID      8 non-null      int64
 1   Name    7 non-null      object
 2   Age     7 non-null      float64
 3   City    8 non-null      object
 4   Marks   7 non-null      float64
dtypes: float64(2), int64(1), object(2)
memory usage: 452.0+ bytes

Task 4:Generate stastistical information for numerical columns.

In [ ]:
# Display statistical summary

df.describe()

           ID        Age      Marks
count    8.00   7.000000   7.000000
mean   104.00  22.000000  87.000000
std      2.00   3.109126   4.690416
min    101.00  19.000000  78.000000
25%    102.75  20.000000  86.000000
50%    104.00  21.000000  88.000000
75%    105.25  23.000000  89.000000
max    107.00  28.000000  93.000000

Task 5:Display dimensions of dataset.

In [ ]:
# Display shape (rows, columns)

df.shape

(8, 5)

Task 6:Display the name of all columns.

In [ ]:
# Display column names

df.columns

Index(['ID', 'Name', 'Age', 'City', 'Marks'], dtype='object')

Task 7:Display the data types of each columns.

In [ ]:
# Display data types

df.dtypes

ID         int64
Name      object
Age      float64
City      object
Marks    float64
dtype: object

Step 4: Check Missing Values

Task 8:Check missing values in each columns.

In [ ]:
# Count missing values in each column

df.isnull().sum()

ID       0
Name     1
Age      1
City     0
Marks    1
dtype: int64

Task 9:Replace missing value in the marks columns.

In [ ]:
df["Marks"] = df["Marks"].fillna(df["Marks"].mean())

df

    ID    Name   Age     City  Marks
0  101   Rahul  20.0    Surat   85.0
1  102   Karan  21.0  Navsari   87.0
2  103    Riya   NaN   Valsad   78.0
3  104    None  19.0  Bharuch   88.0
4  104    Amit  20.0    Surat   88.0
5  105   Priya  22.0  Navsari   87.0
6  106  Krisha  24.0   Valsad   90.0
7  107   Harry  28.0    Surat   93.0

Task 10:Replace missing value in the age columns.

In [ ]:
df["Age"] = df["Age"].fillna(df["Age"].mean())

df

    ID    Name   Age     City  Marks
0  101   Rahul  20.0    Surat   85.0
1  102   Karan  21.0  Navsari   87.0
2  103    Riya  22.0   Valsad   78.0
3  104    None  19.0  Bharuch   88.0
4  104    Amit  20.0    Surat   88.0
5  105   Priya  22.0  Navsari   87.0
6  106  Krisha  24.0   Valsad   90.0
7  107   Harry  28.0    Surat   93.0

Task 11:Replace missing names with the text "Unknown".

In [ ]:
df["Name"] = df["Name"].fillna("Unknown")

df

    ID     Name   Age     City  Marks
0  101    Rahul  20.0    Surat   85.0
1  102    Karan  21.0  Navsari   87.0
2  103     Riya  22.0   Valsad   78.0
3  104  Unknown  19.0  Bharuch   88.0
4  104     Amit  20.0    Surat   88.0
5  105    Priya  22.0  Navsari   87.0
6  106   Krisha  24.0   Valsad   90.0
7  107    Harry  28.0    Surat   93.0

Step 5: Check Duplicate Records

Task 12:Check whether each row is duplicated.

In [ ]:
df.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
dtype: bool

Task 13:Count the total number of duplicate rows.

In [ ]:
# Count duplicate rows

df.duplicated().sum()

np.int64(0)

Step 6: Remove Duplicate Records

Task 14:Remove the duplicate records.

In [ ]:
# Remove duplicate rows permanently

df.drop_duplicates()

df

    ID     Name   Age     City  Marks
0  101    Rahul  20.0    Surat   85.0
1  102    Karan  21.0  Navsari   87.0
2  103     Riya  22.0   Valsad   78.0
3  104  Unknown  19.0  Bharuch   88.0
4  104     Amit  20.0    Surat   88.0
5  105    Priya  22.0  Navsari   87.0
6  106   Krisha  24.0   Valsad   90.0
7  107    Harry  28.0    Surat   93.0

Step 7: Data Cleaning

Task 15:Rename column "Marks" to "Score"

In [ ]:
# Rename Marks column to Score

df.rename(columns={"Marks":"Score"},inplace=True)

df

    ID     Name   Age     City  Score
0  101    Rahul  20.0    Surat   85.0
1  102    Karan  21.0  Navsari   87.0
2  103     Riya  22.0   Valsad   78.0
3  104  Unknown  19.0  Bharuch   88.0
4  104     Amit  20.0    Surat   88.0
5  105    Priya  22.0  Navsari   87.0
6  106   Krisha  24.0   Valsad   90.0
7  107    Harry  28.0    Surat   93.0

Step 8: Data Transformation

Task 16:Convert the age columns from float to integer.

In [ ]:
# Convert Age column into integer datatype

df["Age"] = df["Age"].astype(int)

df.dtypes

ID         int64
Name      object
Age        int64
City      object
Score    float64
dtype: object

Task 17:Create a new column named "Final Score".

In [ ]:
# Increase every student's score by 5 marks

df["Final Score"] = df["Score"] + 5

df

    ID     Name  Age     City  Score  Final Score
0  101    Rahul   20    Surat   85.0         90.0
1  102    Karan   21  Navsari   87.0         92.0
2  103     Riya   22   Valsad   78.0         83.0
3  104  Unknown   19  Bharuch   88.0         93.0
4  104     Amit   20    Surat   88.0         93.0
5  105    Priya   22  Navsari   87.0         92.0
6  106   Krisha   24   Valsad   90.0         95.0
7  107    Harry   28    Surat   93.0         98.0

Task 18:Convert All students names to uppercase.

In [ ]:
# Convert Name to uppercase

df["Name"] = df["Name"].str.upper()

df

    ID     Name  Age     City  Score  Final Score
0  101    RAHUL   20    Surat   85.0         90.0
1  102    KARAN   21  Navsari   87.0         92.0
2  103     RIYA   22   Valsad   78.0         83.0
3  104  UNKNOWN   19  Bharuch   88.0         93.0
4  104     AMIT   20    Surat   88.0         93.0
5  105    PRIYA   22  Navsari   87.0         92.0
6  106   KRISHA   24   Valsad   90.0         95.0
7  107    HARRY   28    Surat   93.0         98.0

Task 19:Convert All students city to lowercase.

In [ ]:
# Convert City names to lowercase

df["City"] = df["City"].str.lower()

df

    ID     Name  Age     City  Score  Final Score
0  101    RAHUL   20    surat   85.0         90.0
1  102    KARAN   21  navsari   87.0         92.0
2  103     RIYA   22   valsad   78.0         83.0
3  104  UNKNOWN   19  bharuch   88.0         93.0
4  104     AMIT   20    surat   88.0         93.0
5  105    PRIYA   22  navsari   87.0         92.0
6  106   KRISHA   24   valsad   90.0         95.0
7  107    HARRY   28    surat   93.0         98.0

Task 20:Remove leading and trailing spaces from city names.

In [ ]:
# Remove extra spaces from Name column

df["City"] = df["City"].str.strip()

df

    ID     Name  Age     City  Score  Final Score
0  101    RAHUL   20    surat   85.0         90.0
1  102    KARAN   21  navsari   87.0         92.0
2  103     RIYA   22   valsad   78.0         83.0
3  104  UNKNOWN   19  bharuch   88.0         93.0
4  104     AMIT   20    surat   88.0         93.0
5  105    PRIYA   22  navsari   87.0         92.0
6  106   KRISHA   24   valsad   90.0         95.0
7  107    HARRY   28    surat   93.0         98.0

Task 21:Sort the dataframe based on the "Final Score" column.

In [ ]:
df.sort_values(by="Final Score",ascending=False)

    ID     Name  Age     City  Score  Final Score
7  107    HARRY   28    surat   93.0         98.0
6  106   KRISHA   24   valsad   90.0         95.0
3  104  UNKNOWN   19  bharuch   88.0         93.0
4  104     AMIT   20    surat   88.0         93.0
1  102    KARAN   21  navsari   87.0         92.0
5  105    PRIYA   22  navsari   87.0         92.0
0  101    RAHUL   20    surat   85.0         90.0
2  103     RIYA   22   valsad   78.0         83.0

Step 9: Save Cleaned Dataset

Task 22:Save the cleaned DataFrame as a new CSV File.

In [ ]:
# Save cleaned dataset into a new CSV file

df.to_csv("cleaned_students.csv",index=False)

print("Dataset saved successfully")

Dataset saved successfully