Enrollment No.:240840116005

Practical-1:Study the Data Analytics lifecycle and perform data acquisition from CSV, Excel, and JSON files using Pandas.

Step 1:Import the Pandas Library

In [23]:
# import pandas
# pd is module of python library
import pandas as pd

Step 2:Create Sample Data

In [24]:
# data is object.
# Create a dictionary containing employee information
data={
    "ID": [101,102,103,104,105,106,107],
    "Name": ["Rahul","Karan","Riya","Amit","Priya","Krisha","Harry"],
    "Age": [20,21,19,20,22,24,28],
    "City": ["Surat","Navsari","Valsad","Bharuch","Surat","Navsari","Valsad"],
    "Marks": [85,92,78,88,81,84,90]
}

Step 3:Create a DataFrame

In [25]:
# Convert dictionary into DataFrame
df = pd.DataFrame(data)

df

    ID    Name  Age     City  Marks
0  101   Rahul   20    Surat     85
1  102   Karan   21  Navsari     92
2  103    Riya   19   Valsad     78
3  104    Amit   20  Bharuch     88
4  105   Priya   22    Surat     81
5  106  Krisha   24  Navsari     84
6  107   Harry   28   Valsad     90

Step 4:Save Data as an CSV File

In [26]:
# Save DataFrame as CSV file

df.to_csv("students.csv",index=False)

print("CSV file created successfully.")

CSV file created successfully.

Step 5:Save Data as an Excel File

In [27]:
# Save DataFrame as Excel file

df.to_excel("students.xlsx",index=False)

print("Excel file created successfully.")

Excel file created successfully.

Step 6:Save data as a JSON File

In [28]:
#Save Data as an JSON File.

df.to_json("students.json", orient="records",indent=4)

print("JSON file created successfully.")

JSON file created successfully.

Step 7:Read the CSV File

In [29]:
# Read CSV file using pandas

df_csv = pd.read_csv("students.csv")

# Display CSV data

df_csv

    ID    Name  Age     City  Marks
0  101   Rahul   20    Surat     85
1  102   Karan   21  Navsari     92
2  103    Riya   19   Valsad     78
3  104    Amit   20  Bharuch     88
4  105   Priya   22    Surat     81
5  106  Krisha   24  Navsari     84
6  107   Harry   28   Valsad     90

Step 8:Read the Excel File

In [30]:
# Read Excel file using pandas

df_excel = pd.read_excel("students.xlsx")

# Display Excel data

df_excel

    ID    Name  Age     City  Marks
0  101   Rahul   20    Surat     85
1  102   Karan   21  Navsari     92
2  103    Riya   19   Valsad     78
3  104    Amit   20  Bharuch     88
4  105   Priya   22    Surat     81
5  106  Krisha   24  Navsari     84
6  107   Harry   28   Valsad     90

Step 9:Read the JSON File

In [31]:
# Read JSON file using pandas

df_json = pd.read_json("students.json")

# Display JSON data

df_json

    ID    Name  Age     City  Marks
0  101   Rahul   20    Surat     85
1  102   Karan   21  Navsari     92
2  103    Riya   19   Valsad     78
3  104    Amit   20  Bharuch     88
4  105   Priya   22    Surat     81
5  106  Krisha   24  Navsari     84
6  107   Harry   28   Valsad     90

Step 10:Display the First Five Records

In [32]:
# Show first five rows

df_csv.head()

    ID   Name  Age     City  Marks
0  101  Rahul   20    Surat     85
1  102  Karan   21  Navsari     92
2  103   Riya   19   Valsad     78
3  104   Amit   20  Bharuch     88
4  105  Priya   22    Surat     81

Step 11:Display the Last Five Records

In [33]:
# Show last five rows

df_csv.tail()

    ID    Name  Age     City  Marks
2  103    Riya   19   Valsad     78
3  104    Amit   20  Bharuch     88
4  105   Priya   22    Surat     81
5  106  Krisha   24  Navsari     84
6  107   Harry   28   Valsad     90

Step 12:Display information DataFrame

In [34]:
# Display information about CSV dataset

df_csv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ID      7 non-null      int64
 1   Name    7 non-null      object
 2   Age     7 non-null      int64
 3   City    7 non-null      object
 4   Marks   7 non-null      int64
dtypes: int64(3), object(2)
memory usage: 412.0+ bytes

Step 13:Display Statistical Summary

In [35]:
# Display numerical summary

df_csv.describe()

               ID        Age      Marks
count    7.000000   7.000000   7.000000
mean   104.000000  22.000000  85.428571
std      2.160247   3.109126   4.961759
min    101.000000  19.000000  78.000000
25%    102.500000  20.000000  82.500000
50%    104.000000  21.000000  85.000000
75%    105.500000  23.000000  89.000000
max    107.000000  28.000000  92.000000

Step 14:Display Dataset Shape

In [36]:
# Print number of rows and columns

df_csv.shape

(7, 5)

Step 15:Display Column Names

In [37]:
# Print column names

df_csv.columns

Index(['ID', 'Name', 'Age', 'City', 'Marks'], dtype='object')

Step 16:Display Data Types

In [38]:
# Print Data Types

df_csv.dtypes

ID        int64
Name     object
Age       int64
City     object
Marks     int64
dtype: object

Step 17:Check for missing values

In [39]:
# Check missing values

df_csv.isnull().sum()

ID       0
Name     0
Age      0
City     0
Marks    0
dtype: int64

Step 18:Display a Single Column

In [40]:
df_csv["Name"]

0     Rahul
1     Karan
2      Riya
3      Amit
4     Priya
5    Krisha
6     Harry
Name: Name, dtype: object

Step 19:Display Multiple Columns

In [41]:
df_csv[["Name","Age"]]

     Name  Age
0   Rahul   20
1   Karan   21
2    Riya   19
3    Amit   20
4   Priya   22
5  Krisha   24
6   Harry   28

Step 20:Filter Records

In [42]:
df_csv[df_csv["Marks"] > 80]

    ID    Name  Age     City  Marks
0  101   Rahul   20    Surat     85
1  102   Karan   21  Navsari     92
3  104    Amit   20  Bharuch     88
4  105   Priya   22    Surat     81
5  106  Krisha   24  Navsari     84
6  107   Harry   28   Valsad     90

Step 21:Calculate Average Marks

In [43]:
df_csv["Marks"].mean()

np.float64(85.42857142857143)

Step 22:Sort Data

In [44]:
# Sort the dataset in descending order of marks.
df_csv.sort_values(by="Marks", ascending=False)

# sort_values() sorts the dataset.
# by="Marks"specifies the sorting column.
# ascending=False

    ID    Name  Age     City  Marks
1  102   Karan   21  Navsari     92
6  107   Harry   28   Valsad     90
3  104    Amit   20  Bharuch     88
0  101   Rahul   20    Surat     85
5  106  Krisha   24  Navsari     84
4  105   Priya   22    Surat     81
2  103    Riya   19   Valsad     78