Enrollment No.:240840116005

Practical-3:Apply filtering, sorting, aggregation, and GroupBy operations on real-world datasets.

In [ ]:
# Import the Pandas library
# Pandas is used for creating and manipulating DataFrames

import pandas as pd

Create Employee Dataset

In [ ]:
# Create a dictionary containing employee information

data={
    "Emp_ID":[101,102,103,104,105,106,107,108],
    "Name":["Rahul","Priya","Amit","Riya","Karan","Neha","Vivek","Pooja"],
    "Department":["IT","HR","IT","Finance","HR","Finance","IT","HR"],
    "City":["Surat","Navsari","Surat","Valsad","Surat","Navsari","Valsad","Surat"],
    "Salary":[45000,38000,52000,48000,40000,51000,60000,42000],
    "Experience":[2,1,5,4,2,6,8,3]
}

In [ ]:
# Convert the dictionary into a Pandas DataFrame

df = pd.DataFrame(data)

df

   Emp_ID   Name Department     City  Salary  Experience
0     101  Rahul         IT    Surat   45000           2
1     102  Priya         HR  Navsari   38000           1
2     103   Amit         IT    Surat   52000           5
3     104   Riya    Finance   Valsad   48000           4
4     105  Karan         HR    Surat   40000           2
5     106   Neha    Finance  Navsari   51000           6
6     107  Vivek         IT   Valsad   60000           8
7     108  Pooja         HR    Surat   42000           3

Step 1:Display the dataset

In [ ]:
# Display all rows and columns of the DataFrame

df

   Emp_ID   Name Department     City  Salary  Experience
0     101  Rahul         IT    Surat   45000           2
1     102  Priya         HR  Navsari   38000           1
2     103   Amit         IT    Surat   52000           5
3     104   Riya    Finance   Valsad   48000           4
4     105  Karan         HR    Surat   40000           2
5     106   Neha    Finance  Navsari   51000           6
6     107  Vivek         IT   Valsad   60000           8
7     108  Pooja         HR    Surat   42000           3

Step 2:Filter Data

Display Employees from IT Department

In [ ]:
# Display employees who belong to the IT department

df[df["Department"]=="IT"]

   Emp_ID   Name Department    City  Salary  Experience
0     101  Rahul         IT   Surat   45000           2
2     103   Amit         IT   Surat   52000           5
6     107  Vivek         IT  Valsad   60000           8

Display Employees with Salary Greater Than 50,000

In [ ]:
# Display employees whose salary is greater than 50,000

df[df["Salary"]>50000]

   Emp_ID   Name Department     City  Salary  Experience
2     103   Amit         IT    Surat   52000           5
5     106   Neha    Finance  Navsari   51000           6
6     107  Vivek         IT   Valsad   60000           8

Display Employees From Surat

In [ ]:
# Display employees who are working in Surat

df[df["City"]=="Surat"]

   Emp_ID   Name Department   City  Salary  Experience
0     101  Rahul         IT  Surat   45000           2
2     103   Amit         IT  Surat   52000           5
4     105  Karan         HR  Surat   40000           2
7     108  Pooja         HR  Surat   42000           3

Apply Multiple Values

In [ ]:
# Apply multiple conditions:
# Display IT employees whose salary is greater than 50,000

df[(df["Department"]=="IT") & (df["Salary"]>50000)]

   Emp_ID   Name Department    City  Salary  Experience
2     103   Amit         IT   Surat   52000           5
6     107  Vivek         IT  Valsad   60000           8

Step 3: Perform Sorting

Sort by Salary

In [ ]:
# Sort employees according to their salary
# By default, sorting is done in ascending order

df.sort_values(by="Salary")

   Emp_ID   Name Department     City  Salary  Experience
1     102  Priya         HR  Navsari   38000           1
4     105  Karan         HR    Surat   40000           2
7     108  Pooja         HR    Surat   42000           3
0     101  Rahul         IT    Surat   45000           2
3     104   Riya    Finance   Valsad   48000           4
5     106   Neha    Finance  Navsari   51000           6
2     103   Amit         IT    Surat   52000           5
6     107  Vivek         IT   Valsad   60000           8

Sort by ascending order

In [ ]:
# Sort employees according to salary in descending order
# Highest salary will appear first

df.sort_values(by="Salary",ascending=False)

   Emp_ID   Name Department     City  Salary  Experience
6     107  Vivek         IT   Valsad   60000           8
2     103   Amit         IT    Surat   52000           5
5     106   Neha    Finance  Navsari   51000           6
3     104   Riya    Finance   Valsad   48000           4
0     101  Rahul         IT    Surat   45000           2
7     108  Pooja         HR    Surat   42000           3
4     105  Karan         HR    Surat   40000           2
1     102  Priya         HR  Navsari   38000           1

Sort by Department and Salary

In [ ]:
# Sort data first by Department
# Then sort employees within each department by Salary
# Salary is sorted in descending order

df.sort_values(by=["Department","Salary"],ascending=[True,False])

   Emp_ID   Name Department     City  Salary  Experience
5     106   Neha    Finance  Navsari   51000           6
3     104   Riya    Finance   Valsad   48000           4
7     108  Pooja         HR    Surat   42000           3
4     105  Karan         HR    Surat   40000           2
1     102  Priya         HR  Navsari   38000           1
6     107  Vivek         IT   Valsad   60000           8
2     103   Amit         IT    Surat   52000           5
0     101  Rahul         IT    Surat   45000           2

Step 4:Perform Aggregation

Calculate Total Salary

In [ ]:
# Calculate the total salary of all employees

df["Salary"].sum()

np.int64(376000)

Calculate Average Salary

In [ ]:
# Calculate the average salary of all employees

df["Salary"].mean()

np.float64(47000.0)

Find highest Salary

In [ ]:
# Find the highest salary in the dataset

df["Salary"].max()

60000

Find Lowest Salary

In [ ]:
# Find the lowest salary in the dataset

df["Salary"].min()

38000

Count Employees

In [ ]:
# Count the total number of employees

df["Emp_ID"].count()

np.int64(8)

Step 5:Perform GroupBy Operations

Average Salary Department-Wise

In [ ]:
# Calculate the average salary for each department

df.groupby("Department")["Salary"].mean()

Department
Finance    49500.000000
HR         40000.000000
IT         52333.333333
Name: Salary, dtype: float64

Minimum Salary Department-Wise

In [ ]:
# Find the minimum salary in each department

df.groupby("Department")["Salary"].min()

Department
Finance    48000
HR         38000
IT         45000
Name: Salary, dtype: int64

Count the Employees Department-Wise

In [ ]:
# Count the number of employees in each department

df.groupby("Department")["Emp_ID"].count()

Department
Finance    2
HR         3
IT         3
Name: Emp_ID, dtype: int64

Total Salary Department-wise

In [ ]:
# Calculate the total salary for each department

df.groupby("Department")["Salary"].sum()

Department
Finance     99000
HR         120000
IT         157000
Name: Salary, dtype: int64

Maximum Salary Department-wise

In [ ]:
# Find the maximum salary in each department

df.groupby("Department")["Salary"].max()

Department
Finance    51000
HR         42000
IT         60000
Name: Salary, dtype: int64

Minimumn Salary Department-wise

In [ ]:
# Find the manimum salary in each department

df.groupby("Department")["Salary"].min()

Department
Finance    48000
HR         38000
IT         45000
Name: Salary, dtype: int64

Group by City

In [ ]:
# Group employees according to their city
# Calculate the average salary for each city

df.groupby("City")["Salary"].mean()

City
Navsari    44500.0
Surat      44750.0
Valsad     54000.0
Name: Salary, dtype: float64

Step 6:Multiple Aggregation Functions

In [ ]:
# Perform multiple calculations on salary department-wise
# count = number of employees
# sum   = total salary
# mean  = average salary
# max   = highest salary
# min   = lowest salary

df.groupby("Department")["Salary"].agg(["count","sum","mean","max","min"])

            count     sum          mean    max    min
Department
Finance         2   99000  49500.000000  51000  48000
HR              3  120000  40000.000000  42000  38000
IT              3  157000  52333.333333  60000  45000

Step 7:Save CSV file

In [ ]:
# Save the employee DataFrame into a CSV file
# index=False prevents Pandas from adding an extra index column

df.to_csv("Employee_Data.csv",index=False)

# Display a message after successfully creating the CSV file

print("CSV File Created successfully.")

CSV File Created successfully.

Download CSV file

In [56]:
# Import the files module from Google Colab
# It allows us to download files to our computer

df.to_csv("Employee_Data.csv",index=False)

from google.colab import files

# Download the generated CSV file

files.download("Employee_Data.csv")